// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGW9TZC-1WzRJrtGreisdZ36Mq-NHufUY',
    appId: '1:391848145280:web:0a0a79ab4e2a4e2d9b1165',
    messagingSenderId: '391848145280',
    projectId: 'faiz-s-project',
    authDomain: 'faiz-s-project.firebaseapp.com',
    storageBucket: 'faiz-s-project.appspot.com',
    measurementId: 'G-08ZDXPWSR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVSjxlqbHkoQMkUrLEcoyKmc7x7rwTrM',
    appId: '1:391848145280:android:97e44fb73dc5bd9e9b1165',
    messagingSenderId: '391848145280',
    projectId: 'faiz-s-project',
    storageBucket: 'faiz-s-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNHA7pow74twr3cG8kvYSutU6vkGvHdg',
    appId: '1:391848145280:ios:8fbf67b63cf511799b1165',
    messagingSenderId: '391848145280',
    projectId: 'faiz-s-project',
    storageBucket: 'faiz-s-project.appspot.com',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNHA7pow74twr3cG8kvYSutU6vkGvHdg',
    appId: '1:391848145280:ios:27b89a08d66709a09b1165',
    messagingSenderId: '391848145280',
    projectId: 'faiz-s-project',
    storageBucket: 'faiz-s-project.appspot.com',
    iosBundleId: 'com.example.menu.RunnerTests',
  );
}
